server:
  port: 8887
#  servlet:
#    context-path: /config

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RunAppHackaton/MicroservicesConfigs.git
          clone-on-start: true
        default-label: master

#  http://localhost:8887/event-service/default
#  http://<config-server-host>:<config-server-port>/<application-name>/<profile>[/<label>]
#???:
#
#  <config-server-host> - ????, ?? ??????? ????????? Spring Cloud Config Server.
#  <config-server-port> - ????, ?? ??????? ??????? Spring Cloud Config Server.
#  <application-name> - ??? ?????? ??????????.
#  <profile> - ???????, ??? ???????? ?? ?????? ???????? ????????????.
#  <label> - (?????????????) ????? (????????, ?????? git). ???? ?? ???????, ????? ???????????? ????? ?? ????????? (?????? "master").